version: '3'

services:
  api:
    image: registry.gitlab.com/daanhenke/web-disassembler/api
    restart: always
    networks:
      - internal
    env_file:
      - local.env
    depends_on:
      - database
      - service_bus
      - elasticsearch

  analyzer:
    image: registry.gitlab.com/daanhenke/web-disassembler/analyzer
    restart: always
    networks:
      - internal
    env_file:
      - local.env
    depends_on:
      - database
      - service_bus
      - elasticsearch


  search:
    image: registry.gitlab.com/daanhenke/web-disassembler/search
    restart: always
    networks:
      - internal
    env_file:
      - local.env
    depends_on:
      - database
      - service_bus
      - elasticsearch


  reverse_proxy:
    image: registry.gitlab.com/daanhenke/web-disassembler/reverse-proxy
    restart: always
    ports:
      - '3100:3100'
    networks:
      - internal
    depends_on:
      - api

  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=devel
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=WebDisassembler
    ports:
      - '5432:5432'
    volumes:
      - database_storage:/var/lib/postgresql/data
    networks:
      - internal

  service_bus:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - service_bus_storage:/var/lib/rabbitmq/
    networks: 
      - internal

  blob_storage:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    command: 'azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --location /workspace'
    ports:
      - '10000:10000'
      - '10001:10001'
    volumes:
      - blob_storage_storage:/workspace
    networks:
      - internal
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster_name=test

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_storage:/usr/share/elasticsearch/data
    ports:
      - '9201:9200'
    networks:
      - internal

volumes:
  database_storage:
    driver: local
  service_bus_storage:
    driver: local
  blob_storage_storage:
    driver: local
  elasticsearch_storage:
    driver: local

networks:
  internal:
    driver: bridge