version: '3'

services:
  database:
    extends:
      file: ../common-services.yml
      service: database

  service_bus:
    extends:
      file: ../common-services.yml
      service: service_bus
  
  blob_storage:
    extends:
      file: ../common-services.yml
      service: blob_storage
  
  elasticsearch:
    extends:
      file: ../elastic-stack.yml
      service: elasticsearch

  kibana:
    extends:
      file: ../elastic-stack.yml
      service: kibana

  elastic-setup:
    extends:
      file: ../elastic-stack.yml
      service: elastic-setup

  api:
    image: ghcr.io/daanhenke/api:master
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - local.env
    depends_on:
      database:
        condition: service_started  
      service_bus:
        condition: service_started  
      elasticsearch:
        condition: service_healthy

  analyzer:
    image: ghcr.io/daanhenke/analyzer:master
    restart: always
    env_file:
      - local.env
    depends_on:
      database:
        condition: service_started  
      service_bus:
        condition: service_started  
      elasticsearch:
        condition: service_healthy

  search:
    image: ghcr.io/daanhenke/search:master
    restart: always
    env_file:
      - local.env
    depends_on:
      database:
        condition: service_started  
      service_bus:
        condition: service_started 
      elasticsearch:
        condition: service_healthy

  reverse_proxy:
    image: ghcr.io/daanhenke/reverse-proxy:master
    restart: always
    ports:
      - '3100:3100'
    depends_on:
      - api


volumes:
  database_storage:
    driver: local
  service_bus_storage:
    driver: local
  blob_storage_storage:
    driver: local
  elasticsearch_certs:
    driver: local
  elasticsearch_storage:
    driver: local
  kibana_storage:
    driver: local
