version: '3'

services: 
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=devel
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=WebDisassembler
    ports:
      - '5432:5432'
    volumes:
      - database_storage:/var/lib/postgresql/data
    networks:
      - internal

  service_bus:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - service_bus_storage:/var/lib/rabbitmq/
    networks: 
      - internal

volumes:
  database_storage:
    driver: local
  service_bus_storage:
    driver: local

networks:
  internal:
    driver: bridge