version: '3'

services:
  database:
    extends:
      file: Docker/common-services.yml
      service: database

  service_bus:
    extends:
      file: Docker/common-services.yml
      service: service_bus
  
  blob_storage:
    extends:
      file: Docker/common-services.yml
      service: blob_storage
  
  elasticsearch:
    extends:
      file: Docker/elastic-stack.yml
      service: elasticsearch

  kibana:
    extends:
      file: Docker/elastic-stack.yml
      service: kibana

  elastic-setup:
    extends:
      file: Docker/elastic-stack.yml
      service: elastic-setup

volumes:
  database_storage:
    driver: local
  service_bus_storage:
    driver: local
  blob_storage_storage:
    driver: local
  elasticsearch_certs:
    driver: local
  elasticsearch_storage:
    driver: local
  kibana_storage:
    driver: local

networks:
  default:
    name: internal
    external: ${EXPOSE_INTERNAL_SERVICES}
  public:
    external: true
