// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDisassembler.DataStorage.Utility;

#nullable disable

namespace WebDisassembler.DataStorage.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4");

            modelBuilder.Entity("WebDisassembler.DataStorage.Models.Binary", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectOwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("OwnerId", "ProjectId", "Id");

                    b.HasIndex("ProjectOwnerId", "ProjectId");

                    b.ToTable("Binaries");
                });

            modelBuilder.Entity("WebDisassembler.DataStorage.Models.Project", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OwnerId", "Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("WebDisassembler.DataStorage.Models.Section", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BinaryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OwnerId", "ProjectId", "BinaryId", "Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("WebDisassembler.DataStorage.Models.Binary", b =>
                {
                    b.HasOne("WebDisassembler.DataStorage.Models.Project", null)
                        .WithMany("Binaries")
                        .HasForeignKey("ProjectOwnerId", "ProjectId");
                });

            modelBuilder.Entity("WebDisassembler.DataStorage.Models.Project", b =>
                {
                    b.Navigation("Binaries");
                });
#pragma warning restore 612, 618
        }
    }
}
