name: 'Build and push Docker container'
description: ''
inputs:
  container-name:
    description: 'Name of the container, used in tag'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  registry-password:
    required: true

permissions:
  contents: read
  packages: write

runs:
  using: 'composite'
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io/daanhenke
        username: ${{ github.actor }}
        password: ${{ inputs.registry_password }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ghcr.io/daanhenke
    - name: Build and push Docker images
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}   