version: '3'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=devel
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=WebDisassembler
    ports:
      - '5432:5432'
    volumes:
      - database_storage:/var/lib/postgresql/data

  service_bus:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - service_bus_storage:/var/lib/rabbitmq/

  blob_storage:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    command: 'azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --location /workspace'
    ports:
      - '10000:10000'
      - '10001:10001'
    volumes:
      - blob_storage_storage:/workspace
