name: Docker Containers

on:
  push:
    branches:
      - 'master'

jobs:
  build-api-container:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push-docker-container
        with:
          container-name: 'api'
          dockerfile: './Docker/AspNet.Dockerfile'
          project-name: 'WebDisassembler.Api'
          registry-password: ${{ secrets.GITHUB_TOKEN }}
